[server]
host = '0.0.0.0'
port = 8080

[aws]
region = 'eu-central-1'

[s3]
bucket = ''

[database]
host = ''
port = 3306
user = 'admin'
password = ''
dbname = 'suai'

[redis]
host = ''
port = 6379

[dynamodb]
table = ''
partition_key = ''
